//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.CriminalServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchFilter", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class SearchFilter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaxHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaxWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MinHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MinWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] NamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] NationalitiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxAge {
            get {
                return this.MaxAgeField;
            }
            set {
                if ((this.MaxAgeField.Equals(value) != true)) {
                    this.MaxAgeField = value;
                    this.RaisePropertyChanged("MaxAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaxHeight {
            get {
                return this.MaxHeightField;
            }
            set {
                if ((this.MaxHeightField.Equals(value) != true)) {
                    this.MaxHeightField = value;
                    this.RaisePropertyChanged("MaxHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxResults {
            get {
                return this.MaxResultsField;
            }
            set {
                if ((this.MaxResultsField.Equals(value) != true)) {
                    this.MaxResultsField = value;
                    this.RaisePropertyChanged("MaxResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaxWeight {
            get {
                return this.MaxWeightField;
            }
            set {
                if ((this.MaxWeightField.Equals(value) != true)) {
                    this.MaxWeightField = value;
                    this.RaisePropertyChanged("MaxWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinAge {
            get {
                return this.MinAgeField;
            }
            set {
                if ((this.MinAgeField.Equals(value) != true)) {
                    this.MinAgeField = value;
                    this.RaisePropertyChanged("MinAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MinHeight {
            get {
                return this.MinHeightField;
            }
            set {
                if ((this.MinHeightField.Equals(value) != true)) {
                    this.MinHeightField = value;
                    this.RaisePropertyChanged("MinHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MinWeight {
            get {
                return this.MinWeightField;
            }
            set {
                if ((this.MinWeightField.Equals(value) != true)) {
                    this.MinWeightField = value;
                    this.RaisePropertyChanged("MinWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Names {
            get {
                return this.NamesField;
            }
            set {
                if ((object.ReferenceEquals(this.NamesField, value) != true)) {
                    this.NamesField = value;
                    this.RaisePropertyChanged("Names");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Nationalities {
            get {
                return this.NationalitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalitiesField, value) != true)) {
                    this.NationalitiesField = value;
                    this.RaisePropertyChanged("Nationalities");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CriminalServiceReference.ICriminalService")]
    public interface ICriminalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/SearchProfiles", ReplyAction="http://tempuri.org/ICriminalService/SearchProfilesResponse")]
        bool SearchProfiles(WebApplication.CriminalServiceReference.SearchFilter searchFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/SearchProfiles", ReplyAction="http://tempuri.org/ICriminalService/SearchProfilesResponse")]
        System.Threading.Tasks.Task<bool> SearchProfilesAsync(WebApplication.CriminalServiceReference.SearchFilter searchFilter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICriminalServiceChannel : WebApplication.CriminalServiceReference.ICriminalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CriminalServiceClient : System.ServiceModel.ClientBase<WebApplication.CriminalServiceReference.ICriminalService>, WebApplication.CriminalServiceReference.ICriminalService {
        
        public CriminalServiceClient() {
        }
        
        public CriminalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CriminalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CriminalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CriminalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SearchProfiles(WebApplication.CriminalServiceReference.SearchFilter searchFilter) {
            return base.Channel.SearchProfiles(searchFilter);
        }
        
        public System.Threading.Tasks.Task<bool> SearchProfilesAsync(WebApplication.CriminalServiceReference.SearchFilter searchFilter) {
            return base.Channel.SearchProfilesAsync(searchFilter);
        }
    }
}
